name: Super-Linter AutoFix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_GO_MODULES: true
          FIX_GO: true
          FIX_MARKDOWN: true
          FIX_PYTHON_RUFF: true
          FIX_SHELL_SHFMT: true
          ACTIONS_RUNNER_DEBUG: true

      - name: Check for autofixes
        run: |
          if git diff --exit-code; then
            echo "No changes detected. Exiting."
            exit 0
          fi

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create autofix branch
        run: |
          git checkout -b autofix/super-linter
          git add .
          git commit -m "chore: autofix by Super-Linter"

      - name: Push changes
        run: |
          git push origin autofix/super-linter

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: autofix/super-linter
          title: "Autofix: Linter Fixes"
          body: "This PR contains linter fixes automatically generated by Super-Linter."
          labels: autofix
