name: Lint

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      # Configuration can be set in .github/linters/.golangci.yml
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --config=.github/linters/.golangci.yml

      # Configuration can be set in .github/linters/ruff.toml
      # as long as `--config .github/linters/ruff.toml` is added to the args in both Ruff steps
      - uses: astral-sh/ruff-action@v2
        with:
          args: check --fix
      - run: ruff format

      - name: Check for autofixes
        run: |
          if git diff --exit-code; then
            echo "No changes detected. Exiting."
            exit 0
          fi

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: fix linting issues"
          branch: lint-fixes
          delete-branch: true
          title: "chore: fix linting issues"
          body: "This PR contains linter fixes automatically generated by the linter workflow."
