name: Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - name: Set output
        id: macos_sdk
        run: echo "path=$(xcrun --show-sdk-path)" >> $GITHUB_OUTPUT

      - name: Set nightly environment variables
        run: |
          echo "IS_NIGHTLY_BUILD=1" >> $GITHUB_ENV
          echo "GORELEASER_CURRENT_TAG=nightly" >> $GITHUB_ENV
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}

      - name: Delete and recreate nightly tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/nightly"; then
            echo "nightly tag exists. Deleting it..."
            git push origin --delete nightly
            git tag -d nightly
          else
            echo "nightly tag does not exist. Creating it..."
          fi
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag nightly
          git push origin nightly
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          SDK_PATH: ${{ steps.macos_sdk.outputs.path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
